### ISSUE TITLE
Anvil texture depends on moreblocks

### ISSUE THREAD

**Issue by jhcole** [FozLand/cottages#4]
The mod should have its own textures.

**Comment by mootpoint** [comment]
Should we make a new one or use the existing and rename it under cottages?

**Comment by jhcole** [comment]
Maybe we can do better than moreblocks_coal_stone. I'm thinking about changing the nodebox a bit too.

**Comment by jhcole** [comment]
Fixed by c9b0fcb5fd22cbe75c51c29c713e2ca45c7f7516
