### ISSUE TITLE
Sounds don't work on a few nodes

### ISSUE THREAD

**Issue by jhcole** [FozLand/cottages#5]
```
cottages:straw_ground
cottages:loam
cottages:feldweg
```

These nodes don't have sound defined properly. This can cause a server crash in certain circumstances (i.g. hit with a snowball).

**Comment by mootpoint** [comment]
Do we have the sound files and they don't work or do we need sound files

**Comment by jhcole** [comment]
We have the sound files, and they work. See bd873d5
